use_frameworks!

target 'MyFramework_Example' do
  pod 'MyFramework', :path => '../'

  target 'MyFramework_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
